---
# roles/ansible_role_template/tasks/main.yml

- name: Foo bar
  become: true
  block:

    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: foo
        state: present
        update_cache: true
      notify: Reload bar

  tags: [foo, bar]
